config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'books/new'

  get 'books/create'

  resources :books

  get 'welcome/index'

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :category, presence: true
	validates :author, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	@book = Book.new
  def new
	@book = Book.new
  end
  def index
  	@books = Book.all
end
def edit
  @book = Book.find(params[:id])
end
	def show
		@book = Book.find(params[:id])
	end
  def create
		@book = Book.new(book_params)
		if @book.save
			redirect_to @book
		else
			render 'new'
		end
  end
 def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to @book
		else
			render 'edit'
		end
  end
  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end
	private
  	def book_params
    	params.require(:book).permit(:name, :category, :author)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
Edit Book
<%= form_for :book, url: book_path(@book), method: :patch do |f|%>
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited
      this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category  %>
  </p>
 <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  
<% end %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>
<h1>This Library's Books</h1>
 
<table width="300" cellpadding="10" border="1">
  <tr>
    <th>Name</th>
    <th>Category</th>
	<th>Author</th>
	<th colspan="3">Actions</th>
  </tr>
 
  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.category %></td>
	  <td><%= book.author %></td>
	  <td><%= link_to 'Show', book_path(book) %></td>
	  <td><%= link_to 'Edit', edit_book_path(book) %></td>
	  <td><%= link_to 'Remove', book_path(book),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<%= form_for :book, url: books_path do |f| %>
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited
      this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category  %>
  </p>
 <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  
<% end %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<strong><p>Selected Book's Information</p></strong>
<p>
  <strong>name:</strong>
  <%= @book.name %>
</p>
 
<p>
  <strong>category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>author:</strong>
  <%= @book.author %>
</p>
<%= link_to 'Back', books_path %>
<%= link_to 'Edit', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome To This Library</h1>
<%= link_to 'Show All Books', controller: 'books' %>
<br>
<%= link_to 'Add New Book', new_book_path %>